<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org" nsURI="http://org.malai.interactiveSystem/1_0_0/" nsPrefix="org">
  <eSubpackages name="malai" nsURI="http://org.malai.interactiveSystem/1_0_0//org/malai"
      nsPrefix="org_malai">
    <eSubpackages name="interactiveSystem" nsURI="http://org.malai.interactiveSystem/1_0_0//org/malai/interactiveSystem"
        nsPrefix="org_malai_interactiveSystem">
      <eClassifiers xsi:type="ecore:EClass" name="interactiveSystem">
        <eStructuralFeatures xsi:type="ecore:EReference" name="instruments" upperBound="-1"
            eType="ecore:EClass Malai.ecore#//Instrument" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" upperBound="-1"
            eType="ecore:EClass Malai.ecore#//Interaction" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
            eType="ecore:EClass Malai.ecore#//Action" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
            eType="ecore:EClass Malai.ecore#//Event" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="-1"
            eType="ecore:EClass Malai.ecore#//Widget" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" upperBound="-1"
            eType="#//malai/interactiveSystem/LinkWidgetMapping" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LinkWidgetMapping">
        <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1"
            eType="ecore:EClass Malai.ecore#//Link"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="binds" upperBound="-1"
            eType="#//malai/interactiveSystem/TransitionWidgetBinding" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TransitionWidgetBinding">
        <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="1"
            eType="ecore:EClass Malai.ecore#//Transition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="widgetIDs" lowerBound="1"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
