/*
* generated by Xtext
*/
package org;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MalaiStandaloneSetup extends MalaiStandaloneSetupGenerated{

	public static void doSetup() {
		new MalaiStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

