/*
 * generated by Xtext
 */
package org;

import fr.inria.diverse.interactiveSystem.InteractiveSystemPackage;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MalaiRuntimeModule extends org.AbstractMalaiRuntimeModule {
	InteractiveSystemPackage i = InteractiveSystemPackage.eINSTANCE;
}
