/*
 * generated by Xtext
 */
package org.ui.contentassist

import org.ui.contentassist.AbstractMalaiProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class MalaiProposalProvider extends AbstractMalaiProposalProvider {
}
