/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MalaiUiModule extends org.ui.AbstractMalaiUiModule {
	public MalaiUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
