/**
 * generated by Xtext
 */
package org.serializer;

import org.serializer.AbstractMalaiSyntacticSequencer;

@SuppressWarnings("all")
public class MalaiSyntacticSequencer extends AbstractMalaiSyntacticSequencer {
}
