/**
 * generated by Xtext
 */
package org.serializer;

import org.serializer.AbstractMalaiSemanticSequencer;

@SuppressWarnings("all")
public class MalaiSemanticSequencer extends AbstractMalaiSemanticSequencer {
}
