/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.ui.internal.MalaiActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MalaiExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MalaiActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MalaiActivator.getInstance().getInjector(MalaiActivator.ORG_MALAI);
	}
	
}
