/*
* generated by Xtext
*/
package org.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.services.MalaiGrammarAccess;

public class MalaiParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MalaiGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.parser.antlr.internal.InternalMalaiParser createParser(XtextTokenStream stream) {
		return new org.parser.antlr.internal.InternalMalaiParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "interactiveSystem";
	}
	
	public MalaiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MalaiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
